### PR TITLE
Clinical Notes - QEWD-28

### PR DESCRIPTION
**Pull request by DineshPatelLeidos**
Code as at 14-Feb-2017 12:00

### CODE REVIEW

**Comment by tony-shannon** [comment]
Are all those changes in 1 commit @DineshPatelLeidos ?
Should they be split out?

**Comment by DineshPatelLeidos** [comment]
Hi @tony-shannon - the only changes in this commit are for clinical notes.  They are detailed here:
https://github.com/RippleOSI/Qewd-Ripple/pull/18/commits/5dd35c4f4b2652d968b61cbe370847b0d58c99d6

**Comment by tony-shannon** [comment]
ok my misunderstanding then
thanks
Tony

**Comment by DineshPatelLeidos** [comment]
Changes Merged in.

**Pull request closed without merging**
